# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f0cefeca4600e8fe2fa611c7a02d5a8d8e4b5cf72e5a9e834f32b1d1e9bd20a9bfce28179eda7d89907d2add84554ee87168ce396f749ce5ae5a7a2498f4b544

test:
  secret_key_base: b04c00caea2232496613be859111712219fbde96e8b891d7cceabde5c77242652c2b41b587397a2e6d69b9d522dc25010e0c82fb76964fd076c1fc6b9237b68d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
